version: "3.7"
services:
        mosquitto:
                image: znibb/mosquitto-rpi:latest
                deploy:
                        replicas: 1
                        restart_policy:
                                condition: on-failure
                ports:
                        - "1883:1883"
                volumes:
                        - "mosquitto_data:/mosquitto"
                configs:
                        - source: mosquitto
                          target: /etc/mosquitto/mosquitto.conf
                          uid: '0'
                          gid: '0'
                          mode: 0644
                networks:
                        - webnet

volumes:
        mosquitto_data:
                driver: local

configs:
        mosquitto:
                file: ./mosquitto.conf

networks:
        webnet:
