version: "3.7"
services:
  mosquitto:
    image: znibb/mosquitto:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "1883:1883"
    volumes:
      - "data:/mosquitto"
    configs:
      - source: mosquitto_config_v1
        target: /etc/mosquitto/mosquitto.conf
        uid: '0'
        gid: '0'
        mode: 0644

    networks:
      - mosquitto

volumes:
  data:
    driver: local

configs:
  mosquitto_config_v1:
    external: true

networks:
  mosquitto:
    driver: overlay
